# App
spring.application.name=smart-campus-api
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb+srv://pafproject:paf%4012345@cluster0.tywbgdc.mongodb.net/pafDB

# Logging
logging.level.org.springframework=INFO
logging.level.com.smartcampus=DEBUG
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
